---
        - name: "Instala programas"
          ansible.builtin.apt:
            name:
              - krfb
              - printer-driver-escpr
              - printer-driver-brlaser
              - openssh-server
              - deja-dup
              - vlc
              - digikam
              - gimp
              - inkscape
              - gufw
              - yt-dlp
              - vim
              - simple-scan
              - pdfsam
              - plymouth
              - plymouth-themes
              - thunderbird
              - thunderbird-l10n-pt-br
              - hyphen-pt-br
              - mythes-pt-br
            state: present
          tags: instalar

        - name: "Instala o Chrome"
          ansible.builtin.apt:
            deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            state: present
          tags: instalar

        - name: "Instala o RustDesk"
          ansible.builtin.apt:
            deb: https://github.com/rustdesk/rustdesk/releases/download/1.4.3/rustdesk-1.4.3-x86_64.deb
            state: present
          tags: instalar

