---
- name: Cria service menu que permite imprimir fotos diretamente do explorador de arquivos
  copy:
    src: files/print2x2.desktop
    dest: "/usr/share/kio/servicemenus/imprimir.desktop"
    owner: root
    group: root
    mode: '0755'
  tags: kde
